apiVersion: v1
kind: Pod
metadata:
  name: mysql-demo
spec:
  containers:
  - name: mysql-demo
    image: mysql
    ports:
      - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: secrets
            key: password
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: secrets
            key: username
      - name: ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: secrets
            key: rootPassword
      - name: DBNAME
        valueFrom:
          secretKeyRef:
            name: secrets
            key: database
        